import "../globals.css"
import { Inter } from "next/font/google"
import { UserProvider } from "@auth0/nextjs-auth0/client"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Chart",
    description: "Generated by create next app",
}

export default function ChartLayout({ children }: { children: React.ReactNode }) {
    return (
        <UserProvider>
            <section>{children}</section>
        </UserProvider>
    )
}
